name: Activity Log

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Git User
        run: |
          git config --global user.name "iqbalmh18"
          git config --global user.email "iqbalmh18.dev@gmail.com"

      - name: Update Activity Log
        run: |
          date '+%Y-%m-%d %H:%M:%S' >> ACTIVITY.log

      - name: Commit and Push
        run: |
          git add ACTIVITY.log
          git commit -m "log: activity update $(date +'%H:%M')" || exit 0
          git push origin main
